var happyHourArray = [
  {id: 'radiator-whiskey-seattle',
    happyHour:{
      Monday:[["16:00","22:00"],["18:00","26:00"]],
      Tuesday:[["16:00","22:00"],["18:00","26:00"]],
      Wednesday:[["16:00","22:00"],["18:00","26:00"]],
      Thursday:[["16:00","22:00"],["18:00","26:00"]],
      Friday:[["16:00","22:00"],["18:00","26:00"]]
    website: '',
    logo: ''
  },
  {
    id: 'list-seattle',
    happyHour: {
      Sunday:[["00:00"],["23:00"]],
      Monday:[["00:00"],["23:00"]],
      Tuesday:[["16:00","21:00"],["17:30","26:00"]],
      Wednesday:[["16:00","21:00"],["17:30","26:00"]],
      Thursday:[["16:00","21:00"],["17:30","26:00"]],
      Friday:[["16:00"],["17:30"]]
      },
    website: '',
    logo: ''
  },
  {
    id: 'the-zig-zag-café-seattle-2',
    happyHour:{
      Monday:[["17:00"],["19:00"]],
      Tuesday:[["17:00"],["19:00"]],
      Wednesday:[["17:00"],["19:00"]],
      Thursday:[["17:00"],["19:00"]],
      Friday:[["17:00"],["19:00"]]
      },
    website: '',
    logo: ''
  },
  {
    id: 'bottlehouse-seattle',
    happyHour:{
      Monday:[["15:00"],["18:00"]],
      Tuesday:[["15:00"],["18:00"]],
      Wednesday:[["15:00"],["18:00"]],
      Thursday:[["15:00"],["18:00"]],
      Friday:[["15:00"],["18:00"]]
      },
    website: '',
    logo: ''
  },
  {
    id: 'the-sixgill-seattle',
    happyHour:{
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]]
      },
    website: '',
    logo: ''
  },
  {
    id: 'russells-seattle',
    happyHour:{
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
      },
    website: '',
    logo: ''
  },
  {
    id:'the-noble-fir-seattle',
    happyHour: {
      Sunday:[["16:00"],["18:30"]],
      Monday:[["16:00"],["18:30"]],
      Tuesday:[["16:00"],["18:30"]],
      Wednesday:[["16:00"],["18:30"]],
      Thursday:[["16:00"],["18:30"]],
      Friday:[["16:00"],["18:30"]],
      Saturday:[["16:00"],["18:30"]]
      },
    website: '',
    logo: ''
  },
  {
    id:'latona-pub-seattle',
    happyHour:{
      Sunday:[["16:30"],["18:30"]],
      Monday:[["16:00"],["18:30"]],
      Tuesday:[["16:30"],["18:30"]],
      Wednesday:[["16:30"],["18:30"]],
      Thursday:[["16:30"],["18:30"]],
      Friday:[["16:30"],["18:30"]],
      Saturday:[["16:30"],["18:30"]]
      },
    website: '',
    logo: ''
  },
  {
    id:'brouwers-cafe-seattle',
    happyHour:{
      Sunday:[["15:00"],["18:00"]],
      Monday:[["15:00"],["18:00"]],
      Tuesday:[["15:00"],["18:00"]],
      Wednesday:[["15:00"],["18:00"]],
      Thursday:[["15:00"],["18:00"]],
      Friday:[["15:00"],["18:00"]]
      },
    website: '',
    logo: ''
  },
  {
    id:'witness-seattle',
    happyHour: {
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
    },
    website: '',
    logo: ''
  },
  {
    id:'über-tavern-seattle-2',
    happyHour:{
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
    },
    website: '',
    logo: ''
  },
  {
    id:'yoroshiku-seattle-4',
    happyHour:{
      Tuesday:[["17:00"],["18:30"]],
      Wednesday:[["17:00"],["18:30"]],
      Thursday:[["17:00"],["18:30"]],
      Friday:[["17:00"],["18:30"]],
      Saturday:[["17:00"],["18:30"]]
      },
    website: '',
    logo: ''
  },
  {
    id: 'sun-liquor-seattle',
    happyHour:{
      Sunday:[["16:00"],["19:00"]],
      Monday:[["16:00"],["19:00"]],
      Tuesday:[["16:00"],["19:00"]],
      Wednesday:[["16:00"],["19:00"]],
      Thursday:[["16:00"],["19:00"]],
      Friday:[["16:00"],["19:00"]],
      Saturday:[["16:00"],["19:00"]]
    },
    website: '',
    logo: ''
  },
  {
    id: 'betty-seattle',
    happyHour: {
      Sunday:[["16:30"],["18:00"]],
      Monday:[["16:30"],["18:00"]],
      Tuesday:[["16:30"],["18:00"]],
      Wednesday:[["16:30"],["18:00"]],
      Thursday:[["16:30"],["18:00"]],
      Friday:[["16:30"],["18:00"]],
      Saturday:[["16:30"],["18:00"]]
      },
    website: '',
    logo: ''},
  {
    id: 'the-octopus-bar-seattle',
    happyHour:{
      Sunday:[["15:30"],["18:30"]],
      Monday:[["15:30"],["18:30"]],
      Tuesday:[["15:30"],["18:30"]],
      Wednesday:[["15:30"],["18:30"]],
      Thursday:[["15:30"],["18:30"]],
      Friday:[["15:30"],["18:30"]],
      Saturday:[["15:30"],["18:30"]]
      },
    website: '',
    logo: ''},
  {
    id: 'the-forge-lounge-seattle',
    happyHour: {
      Moday:[['15:00'],['19:00']],
      Tuesday:[['15:00'],['19:00']],
      Wednesday:[['15:00'],['19:00']],
      Thursday:[['15:00'],['19:00']],
      Friday:[['15:00'],['19:00']],
      Saturday:[['15:00'],['19:00']],
      Sunday:[['15:00'],['19:00']]
      },
    website: '',
    logo: ''
  },
  {
    id: 'toulouse-petit-seattle',
    happyHour: {
      Moday:[['16:00','22:00'],['18:00','25:00']],
      Tuesday:[['16:00','22:00'],['18:00','25:00']],
      Wednesday:[['16:00','22:00'],['18:00','25:00']],
      Thursday:[['16:00','22:00'],['18:00','25:00']],
      Friday:[['16:00','22:00'],['18:00','25:00']],
      Saturday:[['16:00','22:00'],['18:00','25:00']],
      Sunday:[['16:00','22:00'],['18:00','25:00']]
      },
    website: '',
    logo: ''
  },
  {
    id: 'taylor-shellfish-oyster-bar-seattle',
    happyHour:{
      Moday:[['15:00'],['18:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']]
      },
    website: '',
    logo: ''
  },
  {
    id: 'damn-the-weather-seattle',
    happyHour:{
      Moday:[['15:00'],['18:30']],
      Tuesday:[['15:00'],['18:30']],
      Wednesday:[['15:00'],['18:30']],
      Thursday:[['15:00'],['18:30']],
      Friday:[['15:00'],['18:30']]
      },
    website: '', logo: ''},
  {
    id: 'suika-seattle-seattle',
    happyHour:{
      Tuesday:[['16:00'],['18:30']],
      Thursday:[['16:00'],['18:30']],
      Saterday:[['15:00'],['18:30']],
      Sunday:[['15:00'],['18:30']]
      },
    website: '',
    logo: ''
  },
  {
    id: 'triumph-bar-seattle',
    happyHour:{
      Monday:[['21:00'],['26:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']],
      Saterday:[['15:00'],['18:00']],
      Sunday:[['15:00','22:00'],['18:00','26:00']]
    },
    website: '',
    logo: ''},
  {
    id: 'quinns-seattle',
    happyHour:{
      Monday:[['15:00'],['18:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']],
      Saterday:[['15:00'],['18:00']],
      Sunday:[['15:00'],['18:00']]
      },
    website: '',
    logo: ''
  },
  {
    id: 'sun-liquor-seattle',
    happyHour:{
      Monday:[['16:00'],['19:00']],
      Tuesday:[['16:00'],['19:00']],
      Wednesday:[['16:00'],['19:00']],
      Thursday:[['16:00'],['19:00']],
      Friday:[['16:00'],['19:00']],
      Saterday:[['16:00'],['19:00']],
      Sunday:[['16:00'],['19:00']]
      },
    website: '',
    logo: ''
  },
  {
    id:'the-noble-fir-seattle',
    happyHour: {
      Sunday:[["16:00"],["18:30"]],
      Monday:[["16:00"],["18:30"]],
      Tuesday:[["16:00"],["18:30"]],
      Wednesday:[["16:00"],["18:30"]],
      Thursday:[["16:00"],["18:30"]],
      Friday:[["16:00"],["18:30"]],
      Saturday:[["16:00"],["18:30"]]
    },
    website: '',
    logo: ''}
];
// {id:'the-cozy-nut-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id:'the-noble-fir-seattle', happyHour: '', website: '', logo: ''},
// {id:'hazlewood-seattle', happyHour: '', website: '', logo: ''},
// {id:'ocho-seattle', happyHour: '', website: '', logo: ''},
// {id:'the-gerald-seattle', happyHour: '', website: '', logo: ''},
// {id:'stoneburner-seattle', happyHour: '', website: '', logo: ''},
// {id:'percys-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id:'la-isla-cuisine-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-walrus-and-the-carpenter-seattle', happyHour: '', website: '', logo: ''},
// {id: 'highliner-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-leary-traveler-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ballard-station-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'essex-seattle', happyHour: '', website: '', logo: ''},
// {id: 'kings-hardware-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-tin-hat-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'bastille-cafe-and-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'olafs-seattle', happyHour: '', website: '', logo: ''},
// {id: 'bad-jimmys-brewing-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sixgill-seattle', happyHour: '', website: '', logo: ''},
// {id: 'jolly-roger-taproom-seattle', happyHour: '', website: '', logo: ''},
// {id: '8oz-burger-and-co-seattle-6', happyHour: '', website: '', logo: ''},
// {id: 'the-hideout-seattle', happyHour: '', website: '', logo: ''},
// {id: 'honeyhole-seattle', happyHour: '', website: '', logo: ''},
// {id: '8oz-burger-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'soi-seattle', happyHour: '', website: '', logo: ''},
// {id: 'vitos-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-fireside-room-seattle', happyHour: '', website: '', logo: ''},
// {id: 'jimmys-on-broadway-seattle', happyHour: '', website: '', logo: ''},
// {id: 'moe-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'via-tribunali-seattle', happyHour: '', website: '', logo: ''},
// {id: 'primo-seattle', happyHour: '', website: '', logo: ''},
// {id: 'dunbar-room-seattle', happyHour: '', website: '', logo: ''},
// {id: 'quarter-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ayutthaya-thai-seattle', happyHour: '', website: '', logo: ''},
// {id: 'six-arms-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lotus-asian-kitchen-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'café-presse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'garage-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-hunt-club-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'hot-off-the-coals-queen-anne', happyHour: '', website: '', logo: ''},
// {id: 'harrys-on-the-green-denton', happyHour: '', website: '', logo: ''},
// {id: 'brasserie-brightwell-easton', happyHour: '', website: '', logo: ''},
// {id: 'washington-street-pub-easton', happyHour: '', website: '', logo: ''},
// {id: 'o-shucks-irish-pub-centerville', happyHour: '', website: '', logo: ''},
// {id: '404-taphouse-denton', happyHour: '', website: '', logo: ''},
// {id: 'market-street-public-house-denton', happyHour: '', website: '', logo: ''},
// {id: 'good-guys-sports-bar-centreville', happyHour: '', website: '', logo: ''},
// {id: 'docs-downtown-grille-easton', happyHour: '', website: '', logo: ''},
// {id: 'applebees-easton', happyHour: '', website: '', logo: ''},
// {id: 'docs-riverside-grille-centreville', happyHour: '', website: '', logo: ''},
// {id: 'olive-garden-italian-restaurant-easton-3', happyHour: '', website: '', logo: ''},
// {id: 'bannings-tavern-easton', happyHour: '', website: '', logo: ''},
// {id: 'out-of-the-fire-easton', happyHour: '', website: '', logo: ''},
// {id: 'snappys-bar-and-grille-denton', happyHour: '', website: '', logo: ''},
// {id: 'bartlett-pear-inn-easton', happyHour: '', website: '', logo: ''},
// {id: 'scossa-restaurant-and-lounge-easton', happyHour: '', website: '', logo: ''},
// {id: 'the-bbq-joint-easton', happyHour: '', website: '', logo: ''},
// {id: 'ruby-tuesday-easton', happyHour: '', website: '', logo: ''},
// {id: 'hunters-tavern-easton-2', happyHour: '', website: '', logo: ''},
// {id: 'cabin-club-westlake', happyHour: '', website: '', logo: ''},
// {id: '87-west-2-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-rusty-barrel-westlake', happyHour: '', website: '', logo: ''},
// {id: 'moosehead-saloon-westlake', happyHour: '', website: '', logo: ''},
// {id: 'hooley-house-sports-pub-and-grille-westlake', happyHour: '', website: '', logo: ''},
// {id: 'yard-house-westlake', happyHour: '', website: '', logo: ''},
// {id: 'stella-mia-ristorante-westlake', happyHour: '', website: '', logo: ''},
// {id: 'sangria-y-tapas-bar-and-restaurant-westlake', happyHour: '', website: '', logo: ''},
// {id: 'b-spot-westlake', happyHour: '', website: '', logo: ''},
// {id: 'houlihans-westlake', happyHour: '', website: '', logo: ''},
// {id: 'bar-louie-westlake-2', happyHour: '', website: '', logo: ''},
// {id: 'ironwood-cafe-westlake-4', happyHour: '', website: '', logo: ''},
// {id: 'burntwood-tavern-westlake', happyHour: '', website: '', logo: ''},
// {id: 'time-warp-bar-westlake', happyHour: '', website: '', logo: ''},
// {id: 'brio-tuscan-grille-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-rail-north-olmsted', happyHour: '', website: '', logo: ''},
// {id: 'crabbys-pub-westlake', happyHour: '', website: '', logo: ''},
// {id: 'don-ramon-westlake', happyHour: '', website: '', logo: ''},
// {id: 'mitchells-tavern-westlake', happyHour: '', website: '', logo: ''},
// {id: 'miami-nights-grill-bar-and-lounge-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-wild-goose-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'the-captains-club-eastlake', happyHour: '', website: '', logo: ''},
// {id: 'two-bucks-eastlake', happyHour: '', website: '', logo: ''},
// {id: 'local-tavern-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'croagh-patricks-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'olivor-twist-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'beals-pickles-n-pints-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'twisted-paddy-mentor', happyHour: '', website: '', logo: ''},
// {id: 'nicklebys-round-bar-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'ballantine-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'manhattan-deli-bar-and-grille-willoughby-2', happyHour: '', website: '', logo: ''},
// {id: 'billys-a-cappelli-martini-bar-mentor', happyHour: '', website: '', logo: ''},
// {id: 'paragon-wines-martinis-plates-euclid', happyHour: '', website: '', logo: ''},
// {id: 'the-woodroom-martini-and-wine-bar-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'corks-wine-bar-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'sports-fanatics-willowick', happyHour: '', website: '', logo: ''},
// {id: 'lure-bistro-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'hooley-house-sports-pub-and-grille-mentor', happyHour: '', website: '', logo: ''},
// {id: 'the-1899-pub-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'firehouse-grille-and-pub-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'cask-and-trotter-seattle', happyHour: '', website: '', logo: ''},
// {id: 'feierabend-seattle', happyHour: '', website: '', logo: ''},
// {id: 'brave-horse-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'daniels-broiler-seattle-7', happyHour: '', website: '', logo: ''},
// {id: 'dukes-chowder-house-seattle-9', happyHour: '', website: '', logo: ''},
// {id: 'row-house-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-wurst-place-seattle', happyHour: '', website: '', logo: ''},
// {id: 'chandlers-crabhouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'victory-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lunchbox-laboratory-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'novilhos-brazilian-steak-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'flying-fish-seattle', happyHour: '', website: '', logo: ''},
// {id: 'cuoco-seattle', happyHour: '', website: '', logo: ''},
// {id: '13-coins-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-night-owl-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'osteria-rigoletto-seattle', happyHour: '', website: '', logo: ''},
// {id: 'art-marble-21-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'mollusk-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sitting-room-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-masonry-seattle', happyHour: '', website: '', logo: ''},
// {id: 'red-papaya-ale-and-spirits-seattle', happyHour: '', website: '', logo: ''},
// {id: 'crow-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ten-mercer-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mecca-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'queen-anne-beerhall-seattle', happyHour: '', website: '', logo: ''},
// {id: 'streamline-tavern-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'solo-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pesos-kitchen-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'via-tribunali-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-tin-lizzie-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'buckleys-on-queen-anne-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'mcmenamins-queen-anne-seattle', happyHour: '', website: '', logo: ''},
// {id: 'plaza-garibaldi-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-great-nabob-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-rock-wood-fired-kitchen-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-innkeeper-seattle', happyHour: '', website: '', logo: ''},
// {id: 'bathtub-gin-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'roccos-seattle', happyHour: '', website: '', logo: ''},
// {id: 'wakefield-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'clever-bottle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-whisky-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'rob-roy-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-lost-pelican-seattle', happyHour: '', website: '', logo: ''},
// {id: 'black-bottle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'vittles-neighborhood-bistro-and-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'spur-gastropub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'shortys-seattle', happyHour: '', website: '', logo: ''},
// {id: 'local-360-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'two-bells-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-upstairs-seattle', happyHour: '', website: '', logo: ''},
// {id: 'tavolata-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lava-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pennyroyal-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-bar-shoppe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-pharmacy-seattle', happyHour: '', website: '', logo: ''},
// {id: 'taylor-shellfish-oyster-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'shawn-o-donnells-seattle', happyHour: '', website: '', logo: ''},
// {id: 'good-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'the-faerie-queene-seattle', happyHour: '', website: '', logo: ''},
// {id: 'altstadt-bierhalle-and-brathaus-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pioneer-square-saloon-seattle', happyHour: '', website: '', logo: ''},
// {id: 'brgr-bar-seattle-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-london-plane-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'bar-sajor-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fuel-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'box-house-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'merchants-cafe-and-saloon-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mccoys-firehouse-seattle', happyHour: '', website: '', logo: ''},
// {id: 'collins-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'radici-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fort-st-george-seattle', happyHour: '', website: '', logo: ''},
// {id: 'kaname-izakaya-seattle', happyHour: '', website: '', logo: ''},
// {id: 'maekawa-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'bush-garden-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'joes-bar-and-grill-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ba-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'polar-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'triangle-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'girin-seattle', happyHour: '', website: '', logo: ''},
// {id: 'knuckleheads-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'library-wine-bar-and-bistro-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'jakes-tavern-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'j-christians-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'hard-hat-cafe-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'wood-n-tap-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'mikes-blue-collar-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'sliders-grill-and-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'gaetanos-tavern-on-main-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'westbrook-lobster-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'mikro-hamden', happyHour: '', website: '', logo: ''},
// {id: 'christos-restaurant-and-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'archie-moores-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'o-briens-pub-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'michaels-trattoria-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'e-j-nevins-pub-north-haven', happyHour: '', website: '', logo: ''},
// {id: '99-restaurant-and-pub-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'yale-billiards-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'the-funky-monkey-lounge-cheshire', happyHour: '', website: '', logo: ''},
// {id: 'rosies-cafe-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'liams-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-kraken-bar-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'joey-kitchen-at-university-village-seattle', happyHour: '', website: '', logo: ''},
// {id: 'eureka-seattle-4', happyHour: '', website: '', logo: ''},
// {id: 'mamma-melina-ristorante-pizzeria-seattle', happyHour: '', website: '', logo: ''},
// {id: 'college-inn-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'elemental-pizza-seattle', happyHour: '', website: '', logo: ''},
// {id: 'big-time-brewing-company-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-monkey-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'shultzys-sausage-seattle', happyHour: '', website: '', logo: ''},
// {id: 'flowers-bar-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-district-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'piatti-seattle', happyHour: '', website: '', logo: ''},
// {id: 'blue-moon-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ristorante-doria-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ram-restaurant-and-brewery-seattle-8', happyHour: '', website: '', logo: ''},
// {id: 'earls-on-the-avenue-seattle', happyHour: '', website: '', logo: ''},
// {id: 'finn-maccools-irish-pub-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mars-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'dantes-seattle', happyHour: '', website: '', logo: ''},
// {id: 'reillys-pub-markesan', happyHour: '', website: '', logo: ''},
// {id: 'nortons-of-green-lake-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'gardinas-wine-bar-and-cafe-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'grey-rock-mansion-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'adams-rib-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'mahoneys-restaurant-and-bar-oshkosh-2', happyHour: '', website: '', logo: ''},
// {id: 'fat-joes-fond-du-lac', happyHour: '', website: '', logo: ''},
// {id: 'fox-river-brew-pub-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'eureka-landings-bar-and-grill-eureka', happyHour: '', website: '', logo: ''},
// {id: 'peabodys-ale-house-and-the-sideyard-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'cranky-pats-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'boathouse-pub-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'jorgies-berlin', happyHour: '', website: '', logo: ''},
// {id: 'coliseum-fond-du-lac-2', happyHour: '', website: '', logo: ''},
// {id: 'the-ball-room-portage', happyHour: '', website: '', logo: ''},
// {id: 'friar-tucks-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'millers-tavern-ripon', happyHour: '', website: '', logo: ''},
// {id: 'buffalo-wild-wings-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'the-goose-shot-waupun', happyHour: '', website: '', logo: ''},
// {id: 'legends-sports-bar-and-grill-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'enoteca-ca-de-vén-ravenna-2', happyHour: '', website: '', logo: ''},
// {id: 'caffe-grand-italia-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'bagno-dolce-lucia-marina-di-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'bagno-sottomarino-rivaverde-marina-di-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'mosquito-coast-marina', happyHour: '', website: '', logo: ''},
// {id: 'bar-caffe-corte-cavour-ravenna-2', happyHour: '', website: '', logo: ''},
// {id: 'fricandò-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'hookipa-marina-di-ravenna-3', happyHour: '', website: '', logo: ''},
// {id: 'la-corte-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'fargo-cafè-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'vineria-nuova-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'naturalmente-burger-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'teodora-cafe-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'sclub-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffetteria-delle-rose-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'due-dame-ravenna', happyHour: '', website: '', logo: ''},
// {id: 's-apollinare-di-liverani-carla-silvia-e-pierpaolo-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'tribeca-cafe-di-sanzio-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffè-mattei-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffe-della-lirica-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'wedgwood-ale-house-and-cafe-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'wedgwood-broiler-seattle', happyHour: '', website: '', logo: ''},
// {id: 'hudson-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'coopers-alehouse-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-pub-at-third-place-seattle', happyHour: '', website: '', logo: ''},
// {id: 'old-5th-avenue-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'crepe-cafe-and-wine-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fiddlers-inn-pub-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ravenna-alehouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-maple-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'pies-and-pints-seattle', happyHour: '', website: '', logo: ''},
// {id: 'roosevelt-ale-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-atlantic-crossing-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pair-seattle', happyHour: '', website: '', logo: ''},
// {id: 'latona-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'toronado-seattle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-butcher-and-the-baker-seattle', happyHour: '', website: '', logo: ''},
// {id: 'franks-oyster-house-and-champagne-parlor-seattle', happyHour: '', website: '', logo: ''},
// {id: 'die-bierstube-seattle', happyHour: '', website: '', logo: ''},
// {id: 'bai-pai-seattle', happyHour: '', website: '', logo: ''},
// {id: 'royal-oak-doncaster-2', happyHour: '', website: '', logo: ''},
// {id: 'red-lion-doncaster-2', happyHour: '', website: '', logo: ''},
// {id: 'travellers-rest-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'scarborough-arms-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'the-millstone-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'the-carpenters-arms-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'hops-and-fire-craft-tap-house-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'the-blind-pig-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'applebees-greenwood-4', happyHour: '', website: '', logo: ''},
// {id: 'oaken-barrel-brewing-company-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'buffalo-wild-wings-greenwood-2', happyHour: '', website: '', logo: ''},
// {id: 'bjs-restaurant-and-brewhouse-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'applebees-greenwood-3', happyHour: '', website: '', logo: ''},
// {id: 'scottys-brewhouse-indianapolis-5', happyHour: '', website: '', logo: ''},
// {id: 'robbys-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'hooters-indianapolis-4', happyHour: '', website: '', logo: ''},
// {id: 'smokey-bones-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'murphys-pubhouse-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'wings-etc-indianapolis-4', happyHour: '', website: '', logo: ''},
// {id: 'b-bartons-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'the-cheesecake-factory-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'madison-avenue-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'vino-villa-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'revery-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'hookah-nites-grill-bar-and-hookahs-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'fireside-brewhouse-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'hazlewood-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-noble-fir-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ocho-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-gerald-seattle', happyHour: '', website: '', logo: ''},
// {id: 'stoneburner-seattle', happyHour: '', website: '', logo: ''},
// {id: 'la-isla-cuisine-seattle', happyHour: '', website: '', logo: ''},
// {id: 'percys-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'essex-seattle', happyHour: '', website: '', logo: ''},
// {id: 'rays-boathouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'ballard-station-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'olafs-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-walrus-and-the-carpenter-seattle', happyHour: '', website: '', logo: ''},
// {id: 'kings-hardware-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sloop-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: '8oz-burger-and-co-seattle-6', happyHour: '', website: '', logo: ''},
// {id: 'bastille-cafe-and-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'kickin-boot-whiskey-kitchen-seattle', happyHour: '', website: '', logo: ''},
// {id: 'thunderbird-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sexton-seattle', happyHour: '', website: '', logo: ''},
// {id: 'root-table-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mojos-kitchen428-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-burger-saloon-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-stag-woodland', happyHour: '', website: '', logo: ''},
// {id: 'petes-restaurant-and-brewhouse-woodland', happyHour: '', website: '', logo: ''},
// {id: 'browns-corner-bar-and-grill-woodland', happyHour: '', website: '', logo: ''},
// {id: 'kennys-woodland', happyHour: '', website: '', logo: ''},
{id: 'applebees-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'allstars-sports-bar-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'red-robin-gourmet-burgers-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'morgans-on-main-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-elephant-shack-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'ludys-main-street-bbq-and-catering-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-savory-cafe-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'uvaggio-woodland', happyHour: '',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], logo: ''},
{id: 'court-street-cafe-woodland-5',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'black-bear-diner-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'country-waffles-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'dks-place-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'perrys-cozy-diner-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'ciao-chow-woodland',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'olivers-twist-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-tin-hat-seattle-2',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: '418-public-house-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-ridge-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'über-tavern-seattle-2',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'stumbling-goat-bistro-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'duck-island-ale-house-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-park-public-house-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'el-chupacabra-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-blue-glass-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'phinney-market-pub-and-eatery-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'cornuto-pizzeria-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'barking-dog-alehouse-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-yard-cafe-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: '74th-street-ale-house-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'in-the-red-wine-bar-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'molly-maguires-pub-and-fine-eatery-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'the-angry-beaver-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'waterwheel-lounge-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'west-5-seattle',
happyHour:
Sunday:[[""],[""]],
Monday:[[""],[""]],
Tuesday:[[""],[""]],
Wednesday:[[""],[""]],
Thursday:[[""],[""]],
Friday:[[""],[""]],
Saturday:[[""],[""]], website: '', logo: ''},
{id: 'jaks-grill-seattle',
happyHour:
Monday:[["16:30"],["17:30"]],
Tuesday:[["16:30"],["17:30"]],
Wednesday:[["16:30"],["17:30"]],
Thursday:[["16:30"],["17:30"]],
Friday:[["16:30"],["17:30"]], website: 'http://www.jaksgrill.com/process.asp', logo: 'http://www.jaksgrill.com/i/logo.gif'},
{id: 'talaricos-pizzeria-and-lounge-seattle',
happyHour:
Sunday:[["15:00, 23:00"],["18:00, 25:00"]],
Monday:[["15:00, 23:00"],["18:00, 25:00"]],
Tuesday:[["15:00, 23:00"],["18:00, 25:00"]],
Wednesday:[["15:00, 23:00"],["18:00, 25:00"]],
Thursday:[["15:00, 23:00"],["18:00, 25:00"]],
Friday:[["15:00, 23:00"],["18:00, 25:00"]],
Saturday:[["15:00, 23:00"],["18:00, 25:00"]], website: 'http://talaricospizza.com', logo: 'http://talaricospizza.com/wp-content/themes/Talaricos2013/images/talaricos_logo.png'},
{id: 'the-matador-seattle',
happyHour:
Sunday:[["16:00, 22:00"],["18:00, 25:00"]],
Monday:[["16:00, 22:00"],["18:00, 25:00"]],
Tuesday:[["16:00, 22:00"],["18:00, 25:00"]],
Wednesday:[["16:00, 22:00"],["18:00, 25:00"]],
Thursday:[["16:00, 22:00"],["18:00, 25:00"]],
Friday:[["16:00, 22:00"],["18:00, 25:00"]],
Saturday:[["16:00, 22:00"],["18:00, 25:00"]], website: 'http://thematadorrestaurant.com/menu/happy-hour.pdf', logo: 'http://www.matadorrestaurants.com/images/theme-36/logo.png?mw=200'},
{id: 'fresh-bistro-seattle-2',
happyHour:
Monday:[["18:00"],["25:00"]],
Tuesday:["18:00"],["25:00"]],
Wednesday:["18:00"],["25:00"]],
Thursday:["18:00"],["25:00"]],
Friday:[["17:00, 21:00"],["18:00, 22:00"]],
Saturday:[["17:00, 21:00"],["18:00, 22:00"]], website: 'http://www.freshbistroseattle.com/wp-content/uploads/2016/01/Bar-Food-HH-Drinks-4-9-15-website.pdf', logo: 'http://www.freshbistroseattle.com/wp-content/uploads/2012/10/121020_FBFall-8885.jpg'},
{id: 'shadowland-seattle',
happyHour:
Sunday:[["15:00, 22:00"],["18:00, 24:00"]],
Monday:[["15:00, 22:00"],["18:00, 24:00"]],
Tuesday:[["15:00, 22:00"],["18:00, 24:00"]],
Wednesday:[["15:00, 22:00"],["18:00, 24:00"]],
Thursday:[["15:00, 22:00"],["18:00, 24:00"]],
Friday:[["15:00, 22:00"],["18:00, 24:00"]],
Saturday:[["15:00, 22:00"],["18:00, 24:00"]], website: 'http://shadowlandwest.com/wp-content/uploads/2014/04/Happy-food-tents-new-9-24-13.pdf', logo: 'http://shadowlandwest.com/wp-content/themes/shadowlandwest/images/moonLogo.png'},
{id: 'pizzeria-credo-seattle',
happyHour:
Tuesday:[["16:00"],["18:30"]],
Wednesday:[["16:00"],["18:30"]],
Thursday:[["16:00"],["18:30"]],
Friday:[["16:00"],["18:30"]], website: 'http://pizzeriacredo.com/#happy-hour', logo: 'http://pizzeriacredo.com/wp-content/uploads/2013/05/Top-Logo-xsm2.png'},
{id: 'maono-seattle',
happyHour:
Sunday:[["17:00"],["18:30"]],
Monday:[["17:00"],["18:30"]],
Tuesday:[["17:00"],["18:30"]],
Wednesday:[["17:00"],["18:30"]],
Thursday:[["17:00"],["18:30"]], website: 'http://maono.springhillnorthwest.com/food/happy-hour/', logo: 'http://maono.springhillnorthwest.com/image/logo-big.png'},
{id: 'corner-pocket-seattle',
happyHour:
Sunday:[["15:00"],["18:00"]],
Monday:[["15:00"],["18:00"]],
Tuesday:[["15:00"],["18:00"]],
Wednesday:[["15:00"],["18:00"]],
Thursday:[["15:00"],["18:00"]],
Friday:[["15:00"],["18:00"]],
Saturday:[["15:00"],["18:00"]], website: 'https://www.facebook.com/wscornerpocket', logo: ''},
{id: 'poggie-tavern-seattle',
happyHour:
Sunday:[["17:00"],["19:00"]],
Monday:[["17:00"],["19:00"]],
Tuesday:[["17:00"],["19:00"]],
Wednesday:[["17:00"],["19:00"]],
Thursday:[["17:00"],["19:00"]],
Friday:[["17:00"],["19"]],
Saturday:[["17:00"],["19:00"]], website: 'https://www.facebook.com/pages/Poggie-Tavern/116417008382373', logo: 'https://scontent.xx.fbcdn.net/hprofile-frc3/v/t1.0-1/p320x320/1378449_10202448982528849_1139648770_n.jpg?oh=2a5e33437d4e3b172efb5bee109ae5db&oe=57240827'},
{id: 'the-bridge-seattle-3',
happyHour:
Monday:[["15:00, 23:00"],["18:00, 25:00"]],
Tuesday:[["15:00, 23:00"],["18:00, 25:00"]],
Wednesday:[["15:00, 23:00"],["18:00, 25:00"]],
Thursday:[["15:00, 23:00"],["18:00, 25:00"]],
Friday:[["15:00, 23:00"],["18:00, 25:00"]],
Saturday:[["15:00, 23:00"],["18:00, 25:00"]], website: 'http://www.thebridgeseattle.com/wp-content/uploads/2014/05/HAPPY-HOUR-NO-MORE-SALES-TAX-INCLUDED-2.17.15.pdf', logo: 'http://www.thebridgeseattle.com/wp-content/uploads/2013/06/BridgeLogo.png'},
{id: 'skylark-café-and-club-seattle-2',
happyHour:
Sunday:[["16:00"],["19:00"]],
Monday:[["16:00"],["19:00"]],
Tuesday:[["16:00"],["19:00"]],
Wednesday:[["16:00"],["19:00"]],
Thursday:[["16:00"],["19:00"]],
Friday:[["16:00"],["19:00"]],
Saturday:[["16:00"],["19:00"]], website: 'http://www.skylarkcafe.com/menus/', logo: 'http://static1.squarespace.com/static/525a1569e4b0daa056d0c8a9/t/53a2034de4b01756877c75fb/1456120313707/?format=1500w'},
{id: 'luna-park-cafe-seattle',
happyHour:
Monday:[["15:00"],["18:00"]],
Tuesday:[["15:00"],["18:00"]],
Wednesday:[["15:00"],["18:00"]],
Thursday:[["15:00"],["18:00"]],
Friday:[["15:00"],["18:00"]], website: 'http://www.lunaparkcafe.com/happyhour.html', logo: 'http://www.lunaparkcafe.com/_photos/logo.png'},
{id: 'el-chupacabra-seattle-3',
happyHour:
Sunday:[["16:00,22:00"],["18:00,24:00"]],
Monday:[["16:00,22:00"],["18:00,24:00"]],
Tuesday:[["16:00,22:00"],["18:00,24:00"]],
Wednesday:[["16:00,22:00"],["18:00,24:00"]],
Thursday:[["16:00,22:00"],["18:00,24:00"]],
Friday:[["16:00,22:00"],["18:00,24:00"]],
Saturday:[["16:00,22:00"],["18:00,24:00"]], website: 'http://www.elchupacabraseattle.com/menu/happy-hour/', logo: 'http://www.elchupacabraseattle.com/wp-content/uploads/2015/01/drinks.jpg'},
 ]
