var happyHourArray = [
  {id: 'radiator-whiskey-seattle',
    happyHour:{
      Monday:[["16:00","22:00"],["18:00","26:00"]],//Format [[Happy Hour Start Time],[Happy Hour End time]] days with mutliple happy hour times can add aditional times in the respective arrays as new array items.
      Tuesday:[["16:00","22:00"],["18:00","26:00"]],//Format [[Happy Hour Start Time],[Happy Hour End time]]
      Wednesday:[["16:00","22:00"],["18:00","26:00"]],//Format [[Happy Hour Start Time],[Happy Hour End time]]
      Thursday:[["16:00","22:00"],["18:00","26:00"]],//Format [[Happy Hour Start Time],[Happy Hour End time]]
      Friday:[["16:00","22:00"],["18:00","26:00"]]//Format [[Happy Hour Start Time],[Happy Hour End time]]
      },
    website: 'http://radiatorwhiskey.com/',
    logo: 'http://radiatorwhiskey.com/images/rwlogo.png'
  },
  {
    id: 'list-seattle',
    happyHour: {
      Sunday:[["00:00"],["23:00"]],
      Monday:[["00:00"],["23:00"]],
      Tuesday:[["16:00","21:00"],["17:30","26:00"]],
      Wednesday:[["16:00","21:00"],["17:30","26:00"]],
      Thursday:[["16:00","21:00"],["17:30","26:00"]],
      Friday:[["16:00"],["17:30"]]
      },
    website: 'http://www.listbelltown.com/happyhour.html',
    logo: ''
  },
  {
    id: 'the-zig-zag-café-seattle-2',
    happyHour:{
      Monday:[["17:00"],["19:00"]],
      Tuesday:[["17:00"],["19:00"]],
      Wednesday:[["17:00"],["19:00"]],
      Thursday:[["17:00"],["19:00"]],
      Friday:[["17:00"],["19:00"]]
      },
    website: 'http://zigzagseattle.com/',
    logo: 'http://zigzagseattle.com/images/zzlogo_alone.png'
  },
  {
    id: 'bottlehouse-seattle',
    happyHour:{
      Monday:[["15:00"],["18:00"]],
      Tuesday:[["15:00"],["18:00"]],
      Wednesday:[["15:00"],["18:00"]],
      Thursday:[["15:00"],["18:00"]],
      Friday:[["15:00"],["18:00"]]
      },
    website: 'http://bottlehouseseattle.com/',
    logo: 'http://bottlehouseseattle.com/img/logo.png'
  },
  {
    id: 'the-sixgill-seattle',
    happyHour:{
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]]
      },
    website: 'http://thesixgill.com',
    logo: 'http://thesixgill.com/wp-content/uploads/2016/02/footer-logo.png'
  },
  {
    id: 'russells-seattle',
    happyHour:{
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
      },
    website: 'http://www.russellsseattle.com/',
    logo: 'http://static1.squarespace.com/static/5335eab3e4b0de4b29013608/t/5338b617e4b092d3a372d705/1437504446862/?format=750w'
  },
  {
    id:'the-noble-fir-seattle',
    happyHour: {
      Sunday:[["16:00"],["18:30"]],
      Monday:[["16:00"],["18:30"]],
      Tuesday:[["16:00"],["18:30"]],
      Wednesday:[["16:00"],["18:30"]],
      Thursday:[["16:00"],["18:30"]],
      Friday:[["16:00"],["18:30"]],
      Saturday:[["16:00"],["18:30"]]
      },
    website: 'http://www.thenoblefir.com/',
    logo: 'https://pbs.twimg.com/profile_images/608711897878175744/PPlare0L.jpg'
  },
  {
    id:'latona-pub-seattle',
    happyHour:{
      Sunday:[["16:30"],["18:30"]],
      Monday:[["16:00"],["18:30"]],
      Tuesday:[["16:30"],["18:30"]],
      Wednesday:[["16:30"],["18:30"]],
      Thursday:[["16:30"],["18:30"]],
      Friday:[["16:30"],["18:30"]],
      Saturday:[["16:30"],["18:30"]]
      },
    website: 'http://www.3pubs.com/Latona.html',
    logo: 'http://www.3pubs.com/Latona_files/Latona.png'
  },
  {
    id:'brouwers-cafe-seattle',
    happyHour:{
      Sunday:[["15:00"],["18:00"]],
      Monday:[["15:00"],["18:00"]],
      Tuesday:[["15:00"],["18:00"]],
      Wednesday:[["15:00"],["18:00"]],
      Thursday:[["15:00"],["18:00"]],
      Friday:[["15:00"],["18:00"]]
      },
    website: 'http://brouwerscafe.blogspot.com/',
    logo: 'http://4.bp.blogspot.com/_UO8TWvT3_6Q/SosfwM5Ke1I/AAAAAAAAABM/JYTvcX1sgpI/S1600-R/brouwerslogo_white.jpg'
  },
  {
    id:'witness-seattle',
    happyHour: {
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
    },
    website: 'http://witnessbar.com/',
    logo: 'http://witnessbar.com/wp-content/uploads/2013/08/logo.png'
  },
  {
    id:'über-tavern-seattle-2',
    happyHour:{
      Sunday:[["16:00"],["18:00"]],
      Monday:[["16:00"],["18:00"]],
      Tuesday:[["16:00"],["18:00"]],
      Wednesday:[["16:00"],["18:00"]],
      Thursday:[["16:00"],["18:00"]],
      Friday:[["16:00"],["18:00"]],
      Saturday:[["16:00"],["18:00"]]
    },
    website: 'http://www.uberbier.com/',
    logo: 'http://www.uberbier.com/images/kegs-navigation.jpg'
  },
  {
    id:'yoroshiku-seattle-4',
    happyHour:{
      Tuesday:[["17:00"],["18:30"]],
      Wednesday:[["17:00"],["18:30"]],
      Thursday:[["17:00"],["18:30"]],
      Friday:[["17:00"],["18:30"]],
      Saturday:[["17:00"],["18:30"]]
      },
    website: 'http://yoroshikuseattle.com/',
    logo: 'http://yoroshikuseattle.com/img/logo-horizontal.png'
  },
  {
    id: 'sun-liquor-seattle',
    happyHour:{
      Sunday:[["16:00"],["19:00"]],
      Monday:[["16:00"],["19:00"]],
      Tuesday:[["16:00"],["19:00"]],
      Wednesday:[["16:00"],["19:00"]],
      Thursday:[["16:00"],["19:00"]],
      Friday:[["16:00"],["19:00"]],
      Saturday:[["16:00"],["19:00"]]
    },
    website: 'http://www.sunliquor.com/ourstory/',
    logo: 'http://www.sunliquor.com/img/logo.png'
  },
  {
    id: 'betty-seattle',
    happyHour: {
      Sunday:[["16:30"],["18:00"]],
      Monday:[["16:30"],["18:00"]],
      Tuesday:[["16:30"],["18:00"]],
      Wednesday:[["16:30"],["18:00"]],
      Thursday:[["16:30"],["18:00"]],
      Friday:[["16:30"],["18:00"]],
      Saturday:[["16:30"],["18:00"]]
      },
    website: 'http://www.eatatbetty.com/',
    logo: ''},
  {
    id: 'the-octopus-bar-seattle',
    happyHour:{
      Sunday:[["15:30"],["18:30"]],
      Monday:[["15:30"],["18:30"]],
      Tuesday:[["15:30"],["18:30"]],
      Wednesday:[["15:30"],["18:30"]],
      Thursday:[["15:30"],["18:30"]],
      Friday:[["15:30"],["18:30"]],
      Saturday:[["15:30"],["18:30"]]
      },
    website: 'https://theoctopusbar.com/',
    logo: 'http://www.wallyhood.org/wp-content/uploads/2014/01/photo-25-600x449.jpg'},
  {
    id: 'the-forge-lounge-seattle',
    happyHour: {
      Moday:[['15:00'],['19:00']],
      Tuesday:[['15:00'],['19:00']],
      Wednesday:[['15:00'],['19:00']],
      Thursday:[['15:00'],['19:00']],
      Friday:[['15:00'],['19:00']],
      Saturday:[['15:00'],['19:00']],
      Sunday:[['15:00'],['19:00']]
      },
    website: 'http://www.theforgelounge.com/',
    logo: 'http://www.theforgelounge.com/images/page2-img1.jpg'
  },
  {
    id: 'toulouse-petit-seattle',
    happyHour: {
      Moday:[['16:00','22:00'],['18:00','25:00']],
      Tuesday:[['16:00','22:00'],['18:00','25:00']],
      Wednesday:[['16:00','22:00'],['18:00','25:00']],
      Thursday:[['16:00','22:00'],['18:00','25:00']],
      Friday:[['16:00','22:00'],['18:00','25:00']],
      Saturday:[['16:00','22:00'],['18:00','25:00']],
      Sunday:[['16:00','22:00'],['18:00','25:00']]
      },
    website: 'http://toulousepetit.com/',
    logo: 'http://bg5wx2yuc202yg10std15dl8.wpengine.netdna-cdn.com/wp-content/uploads/sites/11/2015/09/toulouse_logo_gold1.jpg'
  },
  {
    id: 'taylor-shellfish-oyster-bar-seattle',
    happyHour:{
      Moday:[['15:00'],['18:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']]
      },
    website: 'http://www.taylorshellfishfarms.com/',
    logo: 'http://farm9.static.flickr.com/8048/8444955064_db5ffe57b0_o.jpg'
  },
  {
    id: 'damn-the-weather-seattle',
    happyHour:{
      Moday:[['15:00'],['18:30']],
      Tuesday:[['15:00'],['18:30']],
      Wednesday:[['15:00'],['18:30']],
      Thursday:[['15:00'],['18:30']],
      Friday:[['15:00'],['18:30']]
      },
    website: 'http://damntheweather.com/',
    logo: ''
  },
  {
    id: 'suika-seattle-seattle',
    happyHour:{
      Tuesday:[['16:00'],['18:30']],
      Thursday:[['16:00'],['18:30']],
      Saterday:[['15:00'],['18:30']],
      Sunday:[['15:00'],['18:30']]
      },
    website: 'http://suikaseattle.com/',
    logo: ''
  },
  {
    id: 'triumph-bar-seattle',
    happyHour:{
      Monday:[['21:00'],['26:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']],
      Saterday:[['15:00'],['18:00']],
      Sunday:[['15:00','22:00'],['18:00','26:00']]
    },
    website: 'http://triumphbar.com/',
    logo: 'http://triumphbar.com/images/triumph_logo_opti%202.png'},
  {
    id: 'quinns-seattle',
    happyHour:{
      Monday:[['15:00'],['18:00']],
      Tuesday:[['15:00'],['18:00']],
      Wednesday:[['15:00'],['18:00']],
      Thursday:[['15:00'],['18:00']],
      Friday:[['15:00'],['18:00']],
      Saterday:[['15:00'],['18:00']],
      Sunday:[['15:00'],['18:00']]
      },
    website: 'http://www.quinnspubseattle.com/',
    logo: 'http://www.kaleberg.com/seattle/quinns.jpg'
},
{
  id:'the-gerald-seattle',
  happyHour: {
    Sunday:[["16:00","22:30"],["18:00","26:00"]],
    Monday:[["16:00","22:30"],["18:00","26:00"]],
    Tuesday:[["16:00","22:30"],["18:00","26:00"]],
    Wednesday:[["16:00","22:30"],["18:00","26:00"]],
    Thursday:[["16:00","22:30"],["18:00","26:00"]],
    Saturday:[["16:00","22:30"],["18:00","26:00"]]
    },
  website: 'http://thegeraldseattle.com/',
  logo: 'http://thegeraldseattle.com/ResizeImage.aspx?img=/Websites/GeraldTest/WebsiteLogo.gif&h=85'
},
{
  id:'stoneburner-seattle',
  happyHour: {
    Sunday:[["15:00"],["17:00"]],
    Monday:[["15:00"],["17:00"]],
    Tuesday:[["15:00"],["17:00"]],
    Wednesday:[["15:00"],["17:00"]],
    Thursday:[["15:00"],["17:00"]],
    Friday:[["15:00"],["17:00"]],
    Saturday:[["15:00"],["17:00"]]
    },
  website: 'https://www.stoneburnerseattle.com/56301/happy-hour',
  logo: 'https://d17my9ypnvqzep.cloudfront.net/35c5f64e-d137-45e8-a1e4-83d0cf1e97fb/dcbf2502-2d91-40d4-a5f1-1c9241bd6859_m.png'
},
{
  id:'percys-and-co-seattle',
  happyHour: {
    Sunday:[["16:00"],["18:00"]],
    Monday:[["16:00"],["26:00"]],
    Tuesday:[["16:00"],["18:00"]],
    Wednesday:[["16:00"],["18:00"]],
    Thursday:[["16:00"],["18:00"]],
    Saturday:[["16:00"],["18:00"]]
    },
  website: 'http://www.percysseattle.com/',
  logo: 'http://www.percysseattle.com/assets/images/logo.png'
},
{
  id:'la-isla-cuisine-seattle',
  happyHour: {
    Sunday:[["15:00","22:00"],["18:00","25:00"]],
    Monday:[["15:00","22:00"],["18:00","25:00"]],
    Tuesday:[["15:00","22:00"],["18:00","25:00"]],
    Wednesday:[["15:00","22:00"],["18:00","25:00"]],
    Thursday:[["15:00","22:00"],["18:00","25:00"]],
    Friday:[["15:00","22:00"],["18:00","25:00"]],
    Saturday:[["15:00","22:00"],["18:00","25:00"]]
  },
  website: 'http://laislacuisine.com/',
  logo: 'http://laislacuisine.com/wp-content/uploads/2013/03/logo.svg'
},
{
  id: 'the-walrus-and-the-carpenter-seattle',
  happyHour: {
    Monday:[["16:00"],["18:00"]],
    Tuesday:[["16:00"],["18:00"]],
    Wednesday:[["16:00"],["18:00"]],
    Thursday:[["16:00"],["18:00"]]
    },
  website: 'http://www.thewalrusbar.com/',
  logo: 'http://www.thewalrusbar.com/assets/images/home-illustration.png'
},
{
  id: 'highliner-public-house-seattle',
  happyHour: {
    Sunday:[["16:00"],["18:00"]],
    Monday:[["16:00"],["18:00"]],
    Tuesday:[["16:00"],["18:00"]],
    Wednesday:[["16:00"],["18:00"]],
    Thursday:[["16:00"],["18:00"]],
    Friday:[["16:00"],["18:00"]],
    Saturday:[["16:00"],["18:00"]]
    },
  website: 'http://www.highlinerpub.net/',
  logo: 'https://pbs.twimg.com/profile_images/644624425459908608/Q5KQTLg2.png'
},
{
  id: 'the-leary-traveler-seattle',
  happyHour: {
    Monday:[["16:00"],["18:00"]],
    Tuesday:[["16:00"],["18:00"]],
    Wednesday:[["16:00"],["18:00"]],
    Thursday:[["16:00"],["18:00"]],
    Friday:[["16:00"],["18:00"]]
    },
  website: 'http://www.learytraveler.com/home',
  logo: 'https://s3-us-west-2.amazonaws.com/re.leary/logo.icon.lg.png'
},
{
  id: 'ballard-station-public-house-seattle',
  happyHour: {
    Sunday:[["16:00","23:00"],["18:00","26:00"]],
    Monday:[["16:00","23:00"],["18:00","26:00"]],
    Tuesday:[["16:00","23:00"],["18:00","26:00"]],
    Wednesday:[["16:00","23:00"],["18:00","26:00"]],
    Thursday:[["16:00","23:00"],["18:00","26:00"]],
    Friday:[["16:00"],["18:00"]],
    },
  website: 'http://theballardstation.com/',
  logo: 'http://theballardstation.com/wp-content/themes/BallardStation/images/logo.png'
},
{
  id: 'bastille-cafe-and-bar-seattle-2',
  happyHour: {
    Sunday:[["16:30"],["18:00"]],
    Monday:[["16:30","22:00"],["18:00","23:00"]],
    Tuesday:[["16:30","22:00"],["18:00","23:00"]],
    Wednesday:[["16:30","22:00"],["18:00","23:00"]],
    Thursday:[["16:30","22:00"],["18:00","23:00"]],
    Friday:[["16:30"],["18:00"]],
    Saturday:[["16:30"],["18:00"]]
    },
  website: 'http://www.bastilleseattle.com/home',
  logo: 'https://d17my9ypnvqzep.cloudfront.net/35c5f64e-d137-45e8-a1e4-83d0cf1e97fb/a29d5c88-c041-450b-aeb4-d70cc726d242_l.png'
},
{
  id: 'bad-jimmys-brewing-co-seattle',
  happyHour: {
    Sunday:[["22:00"],["24:00"]],
    Monday:[["22:00"],["24:00"]],
    Tuesday:[["22:00"],["24:00"]],
    Wednesday:[["22:00"],["24:00"]],
    Thursday:[["22:00"],["24:00"]]
    },
  website: 'http://www.badjimmysbrewingco.com/#home',
  logo: 'http://static1.squarespace.com/static/533fe1d1e4b0889aa7ac2ca4/t/53b25115e4b0968d2960608e/1404195148957/?format=1000w'
},
{
  id: 'jolly-roger-taproom-seattle',
  happyHour: {
    Monday:[["15:00"],["18:00"]],
    Tuesday:[["15:00"],["18:00"]],
    Wednesday:[["15:00"],["18:00"]],
    Thursday:[["15:00"],["18:00"]],
    Friday:[["15:00"],["18:00"]]
    },
  website: 'http://maritimebrewery.com/',
  logo: 'http://maritimebrewery.com/userimages/49.gif'
},
{
  id: '8oz-burger-and-co-seattle',
  happyHour: {
    Sunday:[["16:00","21:00"],["18:00","22:00"]],
    Monday:[["16:00","21:00"],["18:00","23:00"]],
    Tuesday:[["16:00","21:00"],["18:00","23:00"]],
    Wednesday:[["16:00","21:00"],["18:00","23:00"]],
    Thursday:[["16:00","21:00"],["18:00","23:00"]],
    Friday:[["16:00","21:00"],["18:00","24:00"]],
    Saturday:[["16:00","21:00"],["18:00","24:00"]]
    },
  website: 'http://8ozburgerbarsea.com/',
  logo: 'http://8ozburgerandco.com/wp-content/uploads/2014/08/EW-LOGO.png'
},
{
  id: '8oz-burger-and-co-seattle-6',
  happyHour: {
    Sunday:[["16:00","21:00"],["18:00","22:00"]],
    Monday:[["16:00","21:00"],["18:00","22:00"]],
    Tuesday:[["16:00","21:00"],["18:00","22:00"]],
    Wednesday:[["16:00","21:00"],["18:00","22:00"]],
    Thursday:[["16:00","21:00"],["18:00","22:00"]],
    Friday:[["16:00","21:00"],["18:00","23:00"]],
    Saturday:[["16:00","21:00"],["18:00","23:00"]]
    },
  website: 'http://8ozburgerbarsea.com/',
  logo: 'http://8ozburgerandco.com/wp-content/uploads/2014/08/EW-LOGO.png'
},
{
  id: 'the-hideout-seattle',
  happyHour: {
    Sunday:[["16:00"],["19:00"]],
    Monday:[["16:00"],["19:00"]],
    Tuesday:[["16:00"],["19:00"]],
    Wednesday:[["16:00"],["19:00"]],
    Thursday:[["16:00"],["19:00"]],
    Friday:[["16:00"],["19:00"]],
    Saturday:[["16:00"],["19:00"]]
    },
  website: 'http://www.hideoutseattle.com/',
  logo: 'http://www.hideoutseattle.com/images/img_header.gif'
},
{
  id: 'soi-seattle',
  happyHour: {
    Sunday:[["15:00","22:00"],["18:00","23:00"]],
    Monday:[["15:00","22:00"],["18:00","23:00"]],
    Tuesday:[["15:00","22:00"],["18:00","23:00"]],
    Wednesday:[["15:00","22:00"],["18:00","23:00"]],
    Thursday:[["15:00","22:00"],["18:00","23:00"]],
    Friday:[["15:00","23:00"],["18:00","24:00"]],
    Saturday:[["15:00","23:00"],["18:00","24:00"]]
  },
  website: 'http://www.soicapitolhill.com/',
  logo: 'http://www.soicapitolhill.com/i/soi.png'
},
{
  id: 'vitos-seattle',
  happyHour: {
    Sunday:[["16:00"],["19:00"]],
    Monday:[["16:00"],["19:00"]],
    Tuesday:[["16:00"],["19:00"]],
    Wednesday:[["16:00"],["19:00"]],
    Thursday:[["16:00"],["19:00"]],
    Friday:[["16:00"],["19:00"]],
    Saturday:[["16:00"],["19:00"]]
    },
  website: 'http://vitosseattle.com/',
  logo: 'http://vitosseattle.com/images/pixel.png'
},
{
  id: 'the-fireside-room-seattle',
  happyHour: {
    Sunday:[["16:00"],["18:00"]],
    Monday:[["16:00"],["18:00"]],
    Tuesday:[["16:00"],["18:00"]],
    Wednesday:[["16:00"],["18:00"]],
    Thursday:[["16:00"],["18:00"]],
    Friday:[["16:00"],["18:00"]],
    Saturday:[["16:00"],["18:00"]]
    },
  website: 'http://hotelsorrento.com/food-drink#fireside-room',
  logo: ''
},
{
  id: 'jimmys-on-broadway-seattle',
  happyHour: {
    Sunday:[["15:00","21:00"],["18:00","23:00"]],
    Monday:[["15:00","21:00"],["18:00","23:00"]],
    Tuesday:[["15:00","21:00"],["18:00","23:00"]],
    Wednesday:[["15:00","21:00"],["18:00","23:00"]],
    Thursday:[["15:00","21:00"],["18:00","23:00"]],
    Friday:[["15:00","21:00"],["18:00","23:00"]],
    Saturday:[["15:00","21:00"],["18:00","23:00"]]
    },
  website: 'http://jimmysonbroadway.com/',
  logo: ''
},

];



// {id: 'moe-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'via-tribunali-seattle', happyHour: '', website: '', logo: ''},
// {id: 'primo-seattle', happyHour: '', website: '', logo: ''},
// {id: 'dunbar-room-seattle', happyHour: '', website: '', logo: ''},
// {id: 'quarter-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ayutthaya-thai-seattle', happyHour: '', website: '', logo: ''},
// {id: 'six-arms-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lotus-asian-kitchen-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'café-presse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'garage-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-hunt-club-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'hot-off-the-coals-queen-anne', happyHour: '', website: '', logo: ''},
// {id: 'harrys-on-the-green-denton', happyHour: '', website: '', logo: ''},
// {id: 'brasserie-brightwell-easton', happyHour: '', website: '', logo: ''},
// {id: 'washington-street-pub-easton', happyHour: '', website: '', logo: ''},
// {id: 'o-shucks-irish-pub-centerville', happyHour: '', website: '', logo: ''},
// {id: '404-taphouse-denton', happyHour: '', website: '', logo: ''},
// {id: 'market-street-public-house-denton', happyHour: '', website: '', logo: ''},
// {id: 'good-guys-sports-bar-centreville', happyHour: '', website: '', logo: ''},
// {id: 'docs-downtown-grille-easton', happyHour: '', website: '', logo: ''},
// {id: 'applebees-easton', happyHour: '', website: '', logo: ''},
// {id: 'docs-riverside-grille-centreville', happyHour: '', website: '', logo: ''},
// {id: 'olive-garden-italian-restaurant-easton-3', happyHour: '', website: '', logo: ''},
// {id: 'bannings-tavern-easton', happyHour: '', website: '', logo: ''},
// {id: 'out-of-the-fire-easton', happyHour: '', website: '', logo: ''},
// {id: 'snappys-bar-and-grille-denton', happyHour: '', website: '', logo: ''},
// {id: 'bartlett-pear-inn-easton', happyHour: '', website: '', logo: ''},
// {id: 'scossa-restaurant-and-lounge-easton', happyHour: '', website: '', logo: ''},
// {id: 'the-bbq-joint-easton', happyHour: '', website: '', logo: ''},
// {id: 'ruby-tuesday-easton', happyHour: '', website: '', logo: ''},
// {id: 'hunters-tavern-easton-2', happyHour: '', website: '', logo: ''},
// {id: 'cabin-club-westlake', happyHour: '', website: '', logo: ''},
// {id: '87-west-2-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-rusty-barrel-westlake', happyHour: '', website: '', logo: ''},
// {id: 'moosehead-saloon-westlake', happyHour: '', website: '', logo: ''},
// {id: 'hooley-house-sports-pub-and-grille-westlake', happyHour: '', website: '', logo: ''},
// {id: 'yard-house-westlake', happyHour: '', website: '', logo: ''},
// {id: 'stella-mia-ristorante-westlake', happyHour: '', website: '', logo: ''},
// {id: 'sangria-y-tapas-bar-and-restaurant-westlake', happyHour: '', website: '', logo: ''},
// {id: 'b-spot-westlake', happyHour: '', website: '', logo: ''},
// {id: 'houlihans-westlake', happyHour: '', website: '', logo: ''},
// {id: 'bar-louie-westlake-2', happyHour: '', website: '', logo: ''},
// {id: 'ironwood-cafe-westlake-4', happyHour: '', website: '', logo: ''},
// {id: 'burntwood-tavern-westlake', happyHour: '', website: '', logo: ''},
// {id: 'time-warp-bar-westlake', happyHour: '', website: '', logo: ''},
// {id: 'brio-tuscan-grille-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-rail-north-olmsted', happyHour: '', website: '', logo: ''},
// {id: 'crabbys-pub-westlake', happyHour: '', website: '', logo: ''},
// {id: 'don-ramon-westlake', happyHour: '', website: '', logo: ''},
// {id: 'mitchells-tavern-westlake', happyHour: '', website: '', logo: ''},
// {id: 'miami-nights-grill-bar-and-lounge-westlake', happyHour: '', website: '', logo: ''},
// {id: 'the-wild-goose-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'the-captains-club-eastlake', happyHour: '', website: '', logo: ''},
// {id: 'two-bucks-eastlake', happyHour: '', website: '', logo: ''},
// {id: 'local-tavern-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'croagh-patricks-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'olivor-twist-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'beals-pickles-n-pints-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'twisted-paddy-mentor', happyHour: '', website: '', logo: ''},
// {id: 'nicklebys-round-bar-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'ballantine-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'manhattan-deli-bar-and-grille-willoughby-2', happyHour: '', website: '', logo: ''},
// {id: 'billys-a-cappelli-martini-bar-mentor', happyHour: '', website: '', logo: ''},
// {id: 'paragon-wines-martinis-plates-euclid', happyHour: '', website: '', logo: ''},
// {id: 'the-woodroom-martini-and-wine-bar-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'corks-wine-bar-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'sports-fanatics-willowick', happyHour: '', website: '', logo: ''},
// {id: 'lure-bistro-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'hooley-house-sports-pub-and-grille-mentor', happyHour: '', website: '', logo: ''},
// {id: 'the-1899-pub-willoughby', happyHour: '', website: '', logo: ''},
// {id: 'firehouse-grille-and-pub-willoughby-hills', happyHour: '', website: '', logo: ''},
// {id: 'cask-and-trotter-seattle', happyHour: '', website: '', logo: ''},
// {id: 'feierabend-seattle', happyHour: '', website: '', logo: ''},
// {id: 'brave-horse-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'daniels-broiler-seattle-7', happyHour: '', website: '', logo: ''},
// {id: 'dukes-chowder-house-seattle-9', happyHour: '', website: '', logo: ''},
// {id: 'row-house-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-wurst-place-seattle', happyHour: '', website: '', logo: ''},
// {id: 'chandlers-crabhouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'victory-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lunchbox-laboratory-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'novilhos-brazilian-steak-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'flying-fish-seattle', happyHour: '', website: '', logo: ''},
// {id: 'cuoco-seattle', happyHour: '', website: '', logo: ''},
// {id: '13-coins-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-night-owl-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'osteria-rigoletto-seattle', happyHour: '', website: '', logo: ''},
// {id: 'art-marble-21-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'mollusk-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sitting-room-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-masonry-seattle', happyHour: '', website: '', logo: ''},
// {id: 'red-papaya-ale-and-spirits-seattle', happyHour: '', website: '', logo: ''},
// {id: 'crow-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ten-mercer-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mecca-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'queen-anne-beerhall-seattle', happyHour: '', website: '', logo: ''},
// {id: 'streamline-tavern-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'solo-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pesos-kitchen-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'via-tribunali-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-tin-lizzie-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'buckleys-on-queen-anne-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'mcmenamins-queen-anne-seattle', happyHour: '', website: '', logo: ''},
// {id: 'plaza-garibaldi-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-great-nabob-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-rock-wood-fired-kitchen-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-innkeeper-seattle', happyHour: '', website: '', logo: ''},
// {id: 'bathtub-gin-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'roccos-seattle', happyHour: '', website: '', logo: ''},
// {id: 'wakefield-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'clever-bottle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-whisky-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'rob-roy-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-lost-pelican-seattle', happyHour: '', website: '', logo: ''},
// {id: 'black-bottle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'vittles-neighborhood-bistro-and-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'spur-gastropub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'shortys-seattle', happyHour: '', website: '', logo: ''},
// {id: 'local-360-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'two-bells-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-upstairs-seattle', happyHour: '', website: '', logo: ''},
// {id: 'tavolata-seattle', happyHour: '', website: '', logo: ''},
// {id: 'lava-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pennyroyal-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-bar-shoppe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-pharmacy-seattle', happyHour: '', website: '', logo: ''},
// {id: 'taylor-shellfish-oyster-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'shawn-o-donnells-seattle', happyHour: '', website: '', logo: ''},
// {id: 'good-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'the-faerie-queene-seattle', happyHour: '', website: '', logo: ''},
// {id: 'altstadt-bierhalle-and-brathaus-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pioneer-square-saloon-seattle', happyHour: '', website: '', logo: ''},
// {id: 'brgr-bar-seattle-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-london-plane-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'bar-sajor-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fuel-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'box-house-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'merchants-cafe-and-saloon-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mccoys-firehouse-seattle', happyHour: '', website: '', logo: ''},
// {id: 'collins-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'radici-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fort-st-george-seattle', happyHour: '', website: '', logo: ''},
// {id: 'kaname-izakaya-seattle', happyHour: '', website: '', logo: ''},
// {id: 'maekawa-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'bush-garden-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'joes-bar-and-grill-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ba-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'polar-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'triangle-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'girin-seattle', happyHour: '', website: '', logo: ''},
// {id: 'knuckleheads-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'library-wine-bar-and-bistro-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'jakes-tavern-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'j-christians-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'hard-hat-cafe-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'wood-n-tap-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'mikes-blue-collar-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'sliders-grill-and-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'gaetanos-tavern-on-main-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'westbrook-lobster-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'mikro-hamden', happyHour: '', website: '', logo: ''},
// {id: 'christos-restaurant-and-bar-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'archie-moores-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'o-briens-pub-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'michaels-trattoria-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'e-j-nevins-pub-north-haven', happyHour: '', website: '', logo: ''},
// {id: '99-restaurant-and-pub-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'yale-billiards-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'the-funky-monkey-lounge-cheshire', happyHour: '', website: '', logo: ''},
// {id: 'rosies-cafe-wallingford', happyHour: '', website: '', logo: ''},
// {id: 'liams-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-kraken-bar-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'joey-kitchen-at-university-village-seattle', happyHour: '', website: '', logo: ''},
// {id: 'eureka-seattle-4', happyHour: '', website: '', logo: ''},
// {id: 'mamma-melina-ristorante-pizzeria-seattle', happyHour: '', website: '', logo: ''},
// {id: 'college-inn-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'elemental-pizza-seattle', happyHour: '', website: '', logo: ''},
// {id: 'big-time-brewing-company-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-monkey-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'shultzys-sausage-seattle', happyHour: '', website: '', logo: ''},
// {id: 'flowers-bar-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-district-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'piatti-seattle', happyHour: '', website: '', logo: ''},
// {id: 'blue-moon-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ristorante-doria-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ram-restaurant-and-brewery-seattle-8', happyHour: '', website: '', logo: ''},
// {id: 'earls-on-the-avenue-seattle', happyHour: '', website: '', logo: ''},
// {id: 'finn-maccools-irish-pub-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mars-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'dantes-seattle', happyHour: '', website: '', logo: ''},
// {id: 'reillys-pub-markesan', happyHour: '', website: '', logo: ''},
// {id: 'nortons-of-green-lake-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'gardinas-wine-bar-and-cafe-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'grey-rock-mansion-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'adams-rib-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'mahoneys-restaurant-and-bar-oshkosh-2', happyHour: '', website: '', logo: ''},
// {id: 'fat-joes-fond-du-lac', happyHour: '', website: '', logo: ''},
// {id: 'fox-river-brew-pub-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'eureka-landings-bar-and-grill-eureka', happyHour: '', website: '', logo: ''},
// {id: 'peabodys-ale-house-and-the-sideyard-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'cranky-pats-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'boathouse-pub-green-lake', happyHour: '', website: '', logo: ''},
// {id: 'jorgies-berlin', happyHour: '', website: '', logo: ''},
// {id: 'coliseum-fond-du-lac-2', happyHour: '', website: '', logo: ''},
// {id: 'the-ball-room-portage', happyHour: '', website: '', logo: ''},
// {id: 'friar-tucks-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'millers-tavern-ripon', happyHour: '', website: '', logo: ''},
// {id: 'buffalo-wild-wings-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'the-goose-shot-waupun', happyHour: '', website: '', logo: ''},
// {id: 'legends-sports-bar-and-grill-oshkosh', happyHour: '', website: '', logo: ''},
// {id: 'enoteca-ca-de-vén-ravenna-2', happyHour: '', website: '', logo: ''},
// {id: 'caffe-grand-italia-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'bagno-dolce-lucia-marina-di-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'bagno-sottomarino-rivaverde-marina-di-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'mosquito-coast-marina', happyHour: '', website: '', logo: ''},
// {id: 'bar-caffe-corte-cavour-ravenna-2', happyHour: '', website: '', logo: ''},
// {id: 'fricandò-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'hookipa-marina-di-ravenna-3', happyHour: '', website: '', logo: ''},
// {id: 'la-corte-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'fargo-cafè-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'vineria-nuova-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'naturalmente-burger-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'teodora-cafe-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'sclub-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffetteria-delle-rose-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'due-dame-ravenna', happyHour: '', website: '', logo: ''},
// {id: 's-apollinare-di-liverani-carla-silvia-e-pierpaolo-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'tribeca-cafe-di-sanzio-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffè-mattei-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'caffe-della-lirica-ravenna', happyHour: '', website: '', logo: ''},
// {id: 'wedgwood-ale-house-and-cafe-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'wedgwood-broiler-seattle', happyHour: '', website: '', logo: ''},
// {id: 'hudson-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'coopers-alehouse-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-pub-at-third-place-seattle', happyHour: '', website: '', logo: ''},
// {id: 'old-5th-avenue-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'crepe-cafe-and-wine-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fiddlers-inn-pub-and-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ravenna-alehouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-maple-bar-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'pies-and-pints-seattle', happyHour: '', website: '', logo: ''},
// {id: 'roosevelt-ale-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-atlantic-crossing-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pair-seattle', happyHour: '', website: '', logo: ''},
// {id: 'latona-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'toronado-seattle-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-butcher-and-the-baker-seattle', happyHour: '', website: '', logo: ''},
// {id: 'franks-oyster-house-and-champagne-parlor-seattle', happyHour: '', website: '', logo: ''},
// {id: 'die-bierstube-seattle', happyHour: '', website: '', logo: ''},
// {id: 'bai-pai-seattle', happyHour: '', website: '', logo: ''},
// {id: 'royal-oak-doncaster-2', happyHour: '', website: '', logo: ''},
// {id: 'red-lion-doncaster-2', happyHour: '', website: '', logo: ''},
// {id: 'travellers-rest-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'scarborough-arms-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'the-millstone-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'the-carpenters-arms-doncaster', happyHour: '', website: '', logo: ''},
// {id: 'hops-and-fire-craft-tap-house-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'the-blind-pig-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'applebees-greenwood-4', happyHour: '', website: '', logo: ''},
// {id: 'oaken-barrel-brewing-company-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'buffalo-wild-wings-greenwood-2', happyHour: '', website: '', logo: ''},
// {id: 'bjs-restaurant-and-brewhouse-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'applebees-greenwood-3', happyHour: '', website: '', logo: ''},
// {id: 'scottys-brewhouse-indianapolis-5', happyHour: '', website: '', logo: ''},
// {id: 'robbys-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'hooters-indianapolis-4', happyHour: '', website: '', logo: ''},
// {id: 'smokey-bones-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'murphys-pubhouse-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'wings-etc-indianapolis-4', happyHour: '', website: '', logo: ''},
// {id: 'b-bartons-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'the-cheesecake-factory-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'madison-avenue-pub-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'vino-villa-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'revery-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'hookah-nites-grill-bar-and-hookahs-indianapolis', happyHour: '', website: '', logo: ''},
// {id: 'fireside-brewhouse-greenwood', happyHour: '', website: '', logo: ''},
// {id: 'hazlewood-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-noble-fir-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ocho-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-gerald-seattle', happyHour: '', website: '', logo: ''},
// {id: 'stoneburner-seattle', happyHour: '', website: '', logo: ''},
// {id: 'la-isla-cuisine-seattle', happyHour: '', website: '', logo: ''},
// {id: 'percys-and-co-seattle', happyHour: '', website: '', logo: ''},
// {id: 'essex-seattle', happyHour: '', website: '', logo: ''},
// {id: 'rays-boathouse-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'ballard-station-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'olafs-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-walrus-and-the-carpenter-seattle', happyHour: '', website: '', logo: ''},
// {id: 'kings-hardware-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sloop-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: '8oz-burger-and-co-seattle-6', happyHour: '', website: '', logo: ''},
// {id: 'bastille-cafe-and-bar-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'kickin-boot-whiskey-kitchen-seattle', happyHour: '', website: '', logo: ''},
// {id: 'thunderbird-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-sexton-seattle', happyHour: '', website: '', logo: ''},
// {id: 'root-table-seattle', happyHour: '', website: '', logo: ''},
// {id: 'mojos-kitchen428-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-burger-saloon-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-stag-woodland', happyHour: '', website: '', logo: ''},
// {id: 'petes-restaurant-and-brewhouse-woodland', happyHour: '', website: '', logo: ''},
// {id: 'browns-corner-bar-and-grill-woodland', happyHour: '', website: '', logo: ''},
// {id: 'kennys-woodland', happyHour: '', website: '', logo: ''},
// {id: 'applebees-woodland', happyHour: '', website: '', logo: ''},
// {id: 'allstars-sports-bar-woodland', happyHour: '', website: '', logo: ''},
// {id: 'red-robin-gourmet-burgers-woodland', happyHour: '', website: '', logo: ''},
// {id: 'morgans-on-main-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-elephant-shack-woodland', happyHour: '', website: '', logo: ''},
// {id: 'ludys-main-street-bbq-and-catering-woodland', happyHour: '', website: '', logo: ''},
// {id: 'the-savory-cafe-woodland', happyHour: '', website: '', logo: ''},
// {id: 'uvaggio-woodland', happyHour: '', website: '', logo: ''},
// {id: 'court-street-cafe-woodland-5', happyHour: '', website: '', logo: ''},
// {id: 'black-bear-diner-woodland', happyHour: '', website: '', logo: ''},
// {id: 'country-waffles-woodland', happyHour: '', website: '', logo: ''},
// {id: 'dks-place-woodland', happyHour: '', website: '', logo: ''},
// {id: 'perrys-cozy-diner-woodland', happyHour: '', website: '', logo: ''},
// {id: 'ciao-chow-woodland', happyHour: '', website: '', logo: ''},
// {id: 'olivers-twist-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-tin-hat-seattle-2', happyHour: '', website: '', logo: ''},
// {id: '418-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-ridge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'über-tavern-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'stumbling-goat-bistro-seattle', happyHour: '', website: '', logo: ''},
// {id: 'duck-island-ale-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-park-public-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'el-chupacabra-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-blue-glass-seattle', happyHour: '', website: '', logo: ''},
// {id: 'phinney-market-pub-and-eatery-seattle', happyHour: '', website: '', logo: ''},
// {id: 'cornuto-pizzeria-seattle', happyHour: '', website: '', logo: ''},
// {id: 'barking-dog-alehouse-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-yard-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: '74th-street-ale-house-seattle', happyHour: '', website: '', logo: ''},
// {id: 'in-the-red-wine-bar-seattle', happyHour: '', website: '', logo: ''},
// {id: 'molly-maguires-pub-and-fine-eatery-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-angry-beaver-seattle', happyHour: '', website: '', logo: ''},
// {id: 'waterwheel-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'west-5-seattle', happyHour: '', website: '', logo: ''},
// {id: 'elliott-bay-brewery-and-pub-seattle', happyHour: '', website: '', logo: ''},
// {id: 'jaks-grill-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-matador-seattle', happyHour: '', website: '', logo: ''},
// {id: 'talaricos-pizzeria-and-lounge-seattle', happyHour: '', website: '', logo: ''},
// {id: 'fresh-bistro-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'bang-bar-thai-restaurant-seattle', happyHour: '', website: '', logo: ''},
// {id: 'shadowland-seattle', happyHour: '', website: '', logo: ''},
// {id: 'seattle-fish-company-seattle', happyHour: '', website: '', logo: ''},
// {id: 'pizzeria-credo-seattle', happyHour: '', website: '', logo: ''},
// {id: 'maono-seattle', happyHour: '', website: '', logo: ''},
// {id: 'ittos-tapas-seattle', happyHour: '', website: '', logo: ''},
// {id: 'corner-pocket-seattle', happyHour: '', website: '', logo: ''},
// {id: 'poggie-tavern-seattle', happyHour: '', website: '', logo: ''},
// {id: 'the-bridge-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'coastline-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'the-admiral-bird-seattle', happyHour: '', website: '', logo: ''},
// {id: 'skylark-café-and-club-seattle-2', happyHour: '', website: '', logo: ''},
// {id: 'luna-park-cafe-seattle', happyHour: '', website: '', logo: ''},
// {id: 'el-chupacabra-seattle-3', happyHour: '', website: '', logo: ''},
// {id: 'wildfire-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'georges-on-the-town-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'el-monumento-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'the-uptown-social-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'roots-bistro-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'hardtails-bar-and-grill-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'two-rivers-tavern-georgetown-2', happyHour: '', website: '', logo: ''},
// {id: 'chilis-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'mels-lone-star-lanes-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'fish-city-grill-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'the-hollow-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'jack-allens-kitchen-round-rock', happyHour: '', website: '', logo: ''},
// {id: 'wriggleys-pub-georgetown-3', happyHour: '', website: '', logo: ''},
// {id: 'the-brass-tap-round-rock', happyHour: '', website: '', logo: ''},
// {id: 'eats-on-8th-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'red-horn-coffee-house-and-brewing-company-cedar-park', happyHour: '', website: '', logo: ''},
// {id: 'wine-sensation-round-rock', happyHour: '', website: '', logo: ''},
// {id: 'gumbos-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'la-playa-mexican-restaurant-georgetown', happyHour: '', website: '', logo: ''},
// {id: 'doghouse-drinkery-dog-park-leander', happyHour: '', website: '', logo: ''} ]
